// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yozmbekkrlqvtorfnmqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvem1iZWtrcmxxdnRvcmZubXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTk1MDgsImV4cCI6MjA2NTU5NTUwOH0.z324dQCmrFkVTF-qcJXPWV-RyGqGTOHrf9RiBFQszkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);